# Generated by Django 5.1.5 on 2025-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('github_url', models.CharField(max_length=200)),
                ('current_datetime', models.DateTimeField()),
            ],
        ),
    ]
